<?php


namespace App\Statistics;


use stdClass;

class CvsStatisticsReport extends StatisticsReport
{
    final public function initData(): ?object
    {
        return parent::initData(); // TODO: Change the autogenerated stub
    }

    final public function getData(): array
    {
        return [];
    }
}
