<?php


namespace App\Statistics;


class HtmlStatisticsReport extends StatisticsReport
{
    final public function initData(): ?object
    {
        return parent::initData(); // TODO: Change the autogenerated stub
    }

    final public function getData(): ?array
    {
        return parent::getData(); // TODO: Change the autogenerated stub
    }
}
